/**
 * Real SchoolHub product / demo screenshots.
 * Files live in /public/images/screenshots/
 * Prefer `live-*` assets from the production app when available.
 * width/height keep frames at the capture’s natural aspect (no crop/zoom).
 */
export const screenshots = {
  dashboard: {
    src: "/images/screenshots/live-admin-dashboard.jpg",
    width: 1024,
    height: 478,
    title: "Admin dashboard",
    description:
      "Licence, backups, SA-SAMS, learners, staff, classes, fees, enrolment trends and collections in one overview.",
    alt: "SchoolHub SA admin portal dashboard with metrics, enrolment chart and fee collection",
  },
  analytics: {
    src: "/images/screenshots/live-admin-dashboard.jpg",
    width: 1024,
    height: 478,
    title: "Enrolment & fee analytics",
    description:
      "Student enrolment trends and fee collection charts for leadership reporting.",
    alt: "SchoolHub SA admin dashboard showing enrolment trend and fee collection charts",
  },
  institutions: {
    src: "/images/screenshots/demo-01-open-institutions.png",
    width: 1024,
    height: 576,
    title: "Institutions",
    description: "Select and manage institutions on the platform.",
    alt: "SchoolHub SA institutions selection screen",
  },
  applications: {
    src: "/images/screenshots/demo-02-apply-status.png",
    width: 1024,
    height: 576,
    title: "Online applications",
    description: "Track application status from submission through review.",
    alt: "SchoolHub SA online application status screen",
  },
  enrolment: {
    src: "/images/screenshots/demo-03-enrol-said.png",
    width: 1024,
    height: 576,
    title: "Enrolment",
    description: "Convert accepted applicants into enrolled learners.",
    alt: "SchoolHub SA learner enrolment screen",
  },
  printCollect: {
    src: "/images/screenshots/demo-04-collect-print.png",
    width: 1024,
    height: 576,
    title: "Collect & print",
    description: "Generate institutional documents when you need them.",
    alt: "SchoolHub SA document collection and print workflow",
  },
  familyAcademics: {
    src: "/images/screenshots/demo-05-family-academics.png",
    width: 1024,
    height: 576,
    title: "Family academics",
    description: "Parents and families follow academic progress.",
    alt: "SchoolHub SA parent and family academics view",
  },
  parentFees: {
    src: "/images/screenshots/demo-05-parent-pay.png",
    width: 1024,
    height: 576,
    title: "Parent fees visibility",
    description: "Fee information where enabled for guardians.",
    alt: "SchoolHub SA parent portal fee payment view",
  },
  teacherRegister: {
    src: "/images/screenshots/live-lecturer-dashboard.jpg",
    width: 1024,
    height: 478,
    title: "Lecturer portal",
    description:
      "Mark attendance, capture marks, open groups and message learners from one teaching workspace.",
    alt: "SchoolHub SA lecturer portal dashboard with groups, attendance and marks actions",
  },
  modules: {
    src: "/images/screenshots/demo-07-optional-close.png",
    width: 1024,
    height: 576,
    title: "Modular platform",
    description: "Enable the modules your institution needs.",
    alt: "SchoolHub SA modular platform overview",
  },
  saSams: {
    src: "/images/screenshots/demo-08-sasams.png",
    width: 1024,
    height: 576,
    title: "SA-SAMS roadmap",
    description: "South African administration integration on the roadmap.",
    alt: "SchoolHub SA SA-SAMS integration roadmap visual",
  },
  sla: {
    src: "/images/screenshots/demo-09-sla.png",
    width: 1024,
    height: 576,
    title: "Support & SLA",
    description: "Service backed by Cyber Developers.",
    alt: "SchoolHub SA service level agreement overview",
  },
  timetable: {
    src: "/images/screenshots/demo-10-timetable.png",
    width: 1024,
    height: 576,
    title: "Timetables",
    description: "Class, learner and teacher / lecturer schedules.",
    alt: "SchoolHub SA timetable management screen",
  },
  studentLogin: {
    src: "/images/screenshots/live-student-login.jpg",
    width: 1024,
    height: 468,
    title: "Student portal sign-in",
    description:
      "Institution-branded learner login with access to timetable, results, fees and notices.",
    alt: "SchoolHub SA student portal login screen",
  },
  assignments: {
    src: "/images/screenshots/demo-12-assignment.png",
    width: 1024,
    height: 576,
    title: "Assignments",
    description: "View, submit and track homework online.",
    alt: "SchoolHub SA student homework assignment submission screen",
  },
  results: {
    src: "/images/screenshots/live-admin-dashboard.jpg",
    width: 1024,
    height: 478,
    title: "Reporting & analytics",
    description:
      "Enrolment trends and fee collection reporting from live institutional data.",
    alt: "SchoolHub SA reporting charts for enrolment and fee collection",
  },
  messages: {
    src: "/images/screenshots/demo-14-messages.png",
    width: 1024,
    height: 576,
    title: "Internal messaging",
    description: "Communication between educators and learners.",
    alt: "SchoolHub SA internal messaging conversation screen",
  },
  payroll: {
    src: "/images/screenshots/demo-15-payroll.png",
    width: 1024,
    height: 576,
    title: "HR payroll",
    description: "Payslip preview and payroll runs for staff.",
    alt: "SchoolHub SA HR payroll and payslip preview screen",
  },
  paperSavings: {
    src: "/images/screenshots/demo-16-paper-savings.png",
    width: 1024,
    height: 576,
    title: "Less paper, better admin",
    description: "Print when you need it — not a copy for every household.",
    alt: "SchoolHub SA paper savings and digital documents promotion",
  },
  collegeStudent: {
    src: "/images/screenshots/live-student-dashboard.jpg",
    width: 1024,
    height: 505,
    title: "Student portal",
    description:
      "Attendance, averages, fees, assignments, timetable and academic progress for learners.",
    alt: "SchoolHub SA student portal dashboard with student card, attendance and progress",
  },
  cloudHosted: {
    src: "/images/screenshots/demo-18-cloud-hosted.png",
    width: 1024,
    height: 576,
    title: "Cloud-hosted access",
    description: "Work from campus or home in the browser.",
    alt: "SchoolHub SA cloud-hosted dashboard accessed from laptop",
  },
  backup: {
    src: "/images/screenshots/live-backup-restore.jpg",
    width: 1024,
    height: 505,
    title: "Backup & restore",
    description:
      "Automatic cloud backups, offline packages, schedules and restore points from the admin portal.",
    alt: "SchoolHub SA backup and restore screen with schedules and recent backups",
  },
  smsReminders: {
    src: "/images/screenshots/demo-20-sms-reminders.png",
    width: 1024,
    height: 576,
    title: "Fee reminders",
    description: "Email and SMS fee reminder rules.",
    alt: "SchoolHub SA finance fee reminders with SMS example",
  },
  cloudDocs: {
    src: "/images/screenshots/demo-21-cloud-docs.png",
    width: 1024,
    height: 576,
    title: "Document management",
    description: "Institution documents hosted securely in the cloud.",
    alt: "SchoolHub SA document uploads and cloud storage screen",
  },
  moreReasons: {
    src: "/images/screenshots/demo-22-more-reasons.png",
    width: 1024,
    height: 576,
    title: "Built for real institutions",
    description:
      "Auditability, role-based access, offline grace and multi-campus oversight.",
    alt: "SchoolHub SA features including audit log, roles, offline grace and multi-campus",
  },
  visitors: {
    src: "/images/screenshots/demo-23-visitors.png",
    width: 1024,
    height: 576,
    title: "Visitors book",
    description: "Sign in visitors and manage today's register.",
    alt: "SchoolHub SA visitors book sign-in and today's visitors table",
  },
  leave: {
    src: "/images/screenshots/demo-24-leave.png",
    width: 1024,
    height: 576,
    title: "Leave management",
    description: "Staff leave applications, approvals and balances.",
    alt: "SchoolHub SA staff leave application and HR approval screen",
  },
  studentCard: {
    src: "/images/screenshots/live-student-welcome.jpg",
    width: 1024,
    height: 471,
    title: "Learner identity cards",
    description:
      "Student card with barcode for gate and office use, plus printable PDF.",
    alt: "SchoolHub SA student portal showing barcode student card and metrics",
  },
  certificates: {
    src: "/images/screenshots/demo-26-certificates.png",
    width: 1024,
    height: 576,
    title: "Certificates",
    description: "Issue and download certificates of completion.",
    alt: "SchoolHub SA certificates issue and preview screen",
  },
  lecturerDashboard: {
    src: "/images/screenshots/live-lecturer-dashboard.jpg",
    width: 1024,
    height: 478,
    title: "Lecturer portal",
    description:
      "Teaching workspace for groups, attendance, marks and learner messaging.",
    alt: "SchoolHub SA lecturer portal dashboard",
  },
  studentDashboard: {
    src: "/images/screenshots/live-student-dashboard.jpg",
    width: 1024,
    height: 505,
    title: "Student portal dashboard",
    description:
      "Learner overview with student card, attendance, fees, timetable and academic progress.",
    alt: "SchoolHub SA student portal dashboard",
  },
} as const;

export type ScreenshotKey = keyof typeof screenshots;
